### ISSUE TITLE
java.lang.IllegalStateException: Configuration cannot be changed after the prompt is first displayed.

### ISSUE THREAD

**Issue by alexeyvasilyev** [stkent/amplify#165] opened 2017-01-07 10:24 UTC
Sometimes I see this crash in app logs under different Android version:
Amplify 1.5.0.

```
12-29 20:25:07.827 E/AndroidRuntime( 2560): FATAL EXCEPTION: main
12-29 20:25:07.827 E/AndroidRuntime( 2560): Process: com.myproject, PID: 2560
12-29 20:25:07.827 E/AndroidRuntime( 2560): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myproject/com.myproject.activity.ManageCamerasActivity}: java.lang.IllegalStateException: Configuration cannot be changed after the prompt is first displayed.
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.os.Looper.loop(Looper.java:148)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at java.lang.reflect.Method.invoke(Native Method)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-29 20:25:07.827 E/AndroidRuntime( 2560): Caused by: java.lang.IllegalStateException: Configuration cannot be changed after the prompt is first displayed.
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.github.stkent.amplify.prompt.BasePromptView.applyBaseConfig(SourceFile:279)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.github.stkent.amplify.prompt.BasePromptView.onRestoreInstanceState(SourceFile:147)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.github.stkent.amplify.prompt.DefaultLayoutPromptView.onRestoreInstanceState(SourceFile:85)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.View.dispatchRestoreInstanceState(View.java:14752)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.ViewGroup.dispatchThawSelfOnly(ViewGroup.java:3141)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.github.stkent.amplify.prompt.a.dispatchRestoreInstanceState(SourceFile:161)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.view.View.restoreHierarchyState(View.java:14730)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.Activity.performRestoreInstanceState(Activity.java:963)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
12-29 20:25:07.827 E/AndroidRuntime( 2560): 	... 9 more
```

AndroidManifest.xml
```
        <activity
            android:name="com.alexvas.dvr.activity.ManageCamerasActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:label="@string/manage_title"
            android:launchMode="singleTop"
            android:exported="false"
            tools:ignore="UnusedAttribute">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

```

In Application it is initialized

```
    @Override
    public void onCreate() {
        super.onCreate();

        Amplify.initSharedInstance(this)
               .setFeedbackEmailAddress(getString(R.string.email_support))
               .setFeedbackEmailContentProvider(new AmplifyEmailContentProvider())
               .setAlwaysShow(Features.isDebug())
               .applyAllDefaultRules();
    }
```

In activity onCreate:

```
            try {

                DefaultLayoutPromptView promptView
                        = (DefaultLayoutPromptView) findViewById(R.id.prompt_view);

                if (promptView != null) {
                    promptView.addPromptEventListener(new IEventListener() {
                        @Override
                        public void notifyEventTriggered(@NonNull final IEvent event) {
                        }
                    });
                    Amplify.getSharedInstance().promptIfReady(promptView);
                }

            } catch (Throwable e) {
                e.printStackTrace();
            }
        }
```

**Comment by stkent** [comment] 2017-01-07 14:27
@alexeyvasilyev I think this is probably a dupe of #161, so here are a couple steps to try:

- Upgrade to the bugfix release 1.5.1;
- If you're not already, wrap the code in your `onCreate` method as follows:

```java
@Override
public void onCreate(@Nullable final Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_example);

    if (savedInstanceState == null) {
        // your code here
    }
}
```

Please let me know if that combination resolves the issue. Thanks!

**Comment by stkent** [comment] 2017-01-07 14:29
As a side note, you should be able to remove this code from your implementation:

```java
promptView.addPromptEventListener(new IEventListener() {
    @Override
    public void notifyEventTriggered(@NonNull final IEvent event) {
    }
});
```

since your `notifyEventTriggered` method is a no-op :)

**Comment by alexeyvasilyev** [comment] 2017-01-07 19:35
Thanks for letting me know. Will check 1.5.1 version.
notifyEventTriggered was just an example.

**Comment by stkent** [comment] 2017-01-16 00:04
@alexeyvasilyev poke; did v1.5.1 resolve your issue?

**Comment by alexeyvasilyev** [comment] 2017-01-16 05:57
Looks like yes.

**Comment by stkent** [comment] 2017-01-16 13:31
Great, thanks!

**Closed** 2017-01-16 13:32 UTC
Labels: 1c:code, 2t:bug, 3r:duplicate
